name: Terragrunt Apply

# Default: Manually trigger. Please change to other events if needed
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Set Environment to execute Terraspace"
        required: true
        type: choice
        options: # Add more environment if needed
          - demo
jobs:
  apply:
    name: Terragrunt
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: infrastructure-live/${{ github.event.inputs.environment }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Terraform and Terragrunt
        run: |
          brew install tfenv warrensbox/tap/tgswitch
          tfenv install
          tgswitch

      - name: Check Versions
        run: |
          terragrunt --version
          terraform --version

      - name: Decode/Retrieve common_vars.yaml from Secrets
        run: |
          echo "${{ secrets.COMMON_VARS_YAML }}" | base64 --decode > common_vars.yaml
        working-directory: ./infrastructure-live

      # NOTE: run-all apply --auto-aprove is dangerous action without review Terraform Plan, approval process
      # Only acceptable for learning purpose
      - name: Apply
        run: |
          terragrunt run-all apply --terragrunt-non-interactive
