name: Terragrunt Destroy

# Default: Manually trigger. Please change to other events if needed
on:
  workflow_dispatch:
    inputs:
      working_dir:
        description: "Target Working Dir to execute Terragrunt"
        required: true
        default: "warning"
        type: choice
        options:
          - demo
jobs:
  destroy:
    name: Terragrunt
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.working_dir }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: infrastructure-live/${{ github.event.inputs.working_dir }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Terraform and Terragrunt
        run: |
          brew install tfenv warrensbox/tap/tgswitch
          brew install tfenv tgenv
          tfenv install
          tgswitch

      - name: Check Versions
        run: |
          terragrunt --version
          terraform --version

      - name: Decode/Retrieve common_vars.yaml from Secrets
        run: |
          echo "${{ secrets.COMMON_VARS_YAML }}" | base64 --decode > common_vars.yaml
        working-directory: ./infrastructure-live

      - name: Destroy
        run: |
          terragrunt run-all destroy --auto-aprove
