name: Terragrunt Plan & Validate

# Default: Manually trigger. Please change to other events
on:
  workflow_dispatch:
    inputs:
      working_dir:
        description: "Target Working Dir to execute Terragrunt"
        required: true
        default: "warning"
        type: choice
        options:
          - demo
jobs:
  plan_validate:
    name: Terragrunt
    runs-on: ubuntu-latest
    environment: development
    env:
      TERRAFORM_VERSION: latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: infrastructure-live/${{ github.event.inputs.working_dir }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Terraform and Terragrunt
        run: |
          brew install tfenv warrensbox/tap/tgswitch
          brew install tfenv tgenv
          tfenv install
          tgswitch

      - name: Check Versions
        run: |
          terragrunt --version
          terraform --version
